import Config

# Database URL comes from POSTGRES_URL in config/runtime.exs.
config :echo, Echo.Repo,
  pool_size: 10,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

config :logger, level: :info
config :phoenix, :logger, false

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to loopback ipv4 address prevents access from other machines.
config :echo, EchoWeb.Endpoint,
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "nATExEBdg8XECFsR9ay60GV5TKGgQItuKiljRcjLOjTBINc6U7mhWDBYRfPIYLVs",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:echo, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:echo, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :echo, EchoWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/echo_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :echo, dev_routes: true

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable Axiom logging in development
config :echo,
  axiom_enabled: false

# S3-compatible storage client configuration for development
config :echo, Echo.Storage.S3Client,
  endpoint: "https://storage.railway.app",
  region: "auto",
  bucket: "resilient-trough-ugrud5hg",
  access_key_id: "tid_GAqRSGEvlLLiKIikiSDPnaPKforATcHPojFaePCBBGNOHwafJJ"

config :cors_plug,
  origin: [~r/https?:\/\/localhost(:\d+)?$/],
  max_age: 86400,
  methods: ["GET", "POST", "PATCH", "DELETE", "OPTIONS", "PUT"]

config :echo, :auth,
  username: "admin",
  password: "password",
  secret: "secret"

config :echo, Echo.Agents.Providers.Gemini,
  model: "gemini-3.1-pro-preview",
  log_debug_body: true

config :echo, Echo.Agents.Providers.OpenRouter, log_debug_body: true
