import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :echo, EchoWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: [
    "https://apps.shonei.me",
    "https://shonei.dev",
    "https://apps.shonei.dev",
    "//apps.shonei.me",
    "//shonei.dev"
  ]

# Do not print debug messages in production
config :logger, level: :info
config :phoenix, :logger, false

# Enable dev routes for dashboard and mailbox
config :echo, dev_routes: true

config :echo,
  # Enable Axiom logging
  axiom_enabled: true,

  # Your Axiom dataset name (create this in https://app.axiom.co/datasets)
  axiom_dataset: "logs",

  # Axiom API URL (use https://api.eu.axiom.co for EU region)
  axiom_url: "https://api.axiom.co"


# S3-compatible storage client configuration for production
config :echo, Echo.Storage.S3Client,
  endpoint: System.get_env("S3_ENDPOINT"),
  region: System.get_env("S3_REGION") || "auto",
  bucket: System.get_env("S3_BUCKET"),
  access_key_id: System.get_env("S3_ACCESS_KEY_ID")

config :echo, Echo.Agents.API, model: "gemini-3.1-pro-preview"

config :cors_plug,
  origin: [
    "https://shonei.me",
    "https://shonei.dev",
    "https://apps.shonei.me",
    "https://apps.shonei.dev",
    "https://blogs.shonei.me",
    "https://blogs.shonei.dev"
  ],
  max_age: 86400,
  methods: ["GET", "POST", "PATCH", "DELETE", "OPTIONS", "PUT"]
