import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :echo, EchoWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info
config :phoenix, :logger, false

# Enable dev routes for dashboard and mailbox
config :echo, dev_routes: true

config :echo,
  # Enable Axiom logging
  axiom_enabled: true,

  # Your Axiom API token (get this from https://app.axiom.co/settings/tokens)
  axiom_token: "xaat-93bd5fbe-37a5-413d-9ca4-bd622484ff9f",

  # Your Axiom dataset name (create this in https://app.axiom.co/datasets)
  axiom_dataset: "logs",

  # Axiom API URL (use https://api.eu.axiom.co for EU region)
  axiom_url: "https://api.axiom.co"

config :cors_plug,
  origin: [~r/^https?:\/\/.*\.shonei\.me$/],
  max_age: 86400,
  methods: ["GET", "POST", "PATCH", "DELETE", "OPTIONS"]

# S3-compatible storage client configuration for production
config :echo, Echo.Storage.S3Client,
  endpoint: System.get_env("S3_ENDPOINT"),
  region: System.get_env("S3_REGION") || "auto",
  bucket: System.get_env("S3_BUCKET"),
  access_key_id: System.get_env("S3_ACCESS_KEY_ID")
