import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :echo, EchoWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Enable dev routes for dashboard and mailbox
config :echo, dev_routes: true

config :echo, EchoWeb.Endpoint,
       # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
       http: [ip: {0, 0, 0, 0}, port: 4000],
       check_origin: false,
       code_reloader: false,
       debug_errors: true